#!/usr/bin/env python3
"""Generate ~1000 songs for the ukulele app song library."""
import json, os, re

# Chord database (GCEA ukulele tuning)
CHORDS = {
    'C':     {'name':'C',     'frets':[0,0,0,3], 'fingers':[0,0,0,3]},
    'D':     {'name':'D',     'frets':[2,2,2,0], 'fingers':[1,2,3,0]},
    'E':     {'name':'E',     'frets':[4,4,4,2], 'fingers':[2,3,4,1]},
    'F':     {'name':'F',     'frets':[2,0,1,0], 'fingers':[2,0,1,0]},
    'G':     {'name':'G',     'frets':[0,2,3,2], 'fingers':[0,1,3,2]},
    'A':     {'name':'A',     'frets':[2,1,0,0], 'fingers':[2,1,0,0]},
    'Bb':    {'name':'Bb',    'frets':[3,2,1,1], 'fingers':[3,2,1,1]},
    'B':     {'name':'B',     'frets':[4,3,2,2], 'fingers':[3,2,1,1]},
    'Eb':    {'name':'Eb',    'frets':[0,3,3,1], 'fingers':[0,2,3,1]},
    'Ab':    {'name':'Ab',    'frets':[5,3,4,3], 'fingers':[3,1,2,1]},
    'Am':    {'name':'Am',    'frets':[2,0,0,0], 'fingers':[1,0,0,0]},
    'Bm':    {'name':'Bm',    'frets':[4,2,2,2], 'fingers':[3,1,1,1]},
    'Cm':    {'name':'Cm',    'frets':[0,3,3,3], 'fingers':[0,1,2,3]},
    'Dm':    {'name':'Dm',    'frets':[2,2,1,0], 'fingers':[2,3,1,0]},
    'Em':    {'name':'Em',    'frets':[0,4,3,2], 'fingers':[0,3,2,1]},
    'Fm':    {'name':'Fm',    'frets':[1,0,1,3], 'fingers':[1,0,2,4]},
    'Gm':    {'name':'Gm',    'frets':[0,2,3,1], 'fingers':[0,2,3,1]},
    'F#m':   {'name':'F#m',   'frets':[2,1,2,0], 'fingers':[2,1,3,0]},
    'C#m':   {'name':'C#m',   'frets':[1,4,4,4], 'fingers':[1,2,3,4]},
    'Bbm':   {'name':'Bbm',   'frets':[3,1,1,1], 'fingers':[3,1,1,1]},
    'A7':    {'name':'A7',    'frets':[0,1,0,0], 'fingers':[0,1,0,0]},
    'B7':    {'name':'B7',    'frets':[2,3,2,0], 'fingers':[1,2,3,0]},
    'C7':    {'name':'C7',    'frets':[0,0,0,1], 'fingers':[0,0,0,1]},
    'D7':    {'name':'D7',    'frets':[2,2,2,3], 'fingers':[1,2,3,4]},
    'E7':    {'name':'E7',    'frets':[1,2,0,2], 'fingers':[1,2,0,3]},
    'F7':    {'name':'F7',    'frets':[2,3,1,3], 'fingers':[1,3,0,4]},
    'G7':    {'name':'G7',    'frets':[0,2,1,2], 'fingers':[0,2,1,3]},
    'Am7':   {'name':'Am7',   'frets':[0,0,0,0], 'fingers':[0,0,0,0]},
    'Bm7':   {'name':'Bm7',   'frets':[2,2,2,2], 'fingers':[1,1,1,1]},
    'Cm7':   {'name':'Cm7',   'frets':[3,3,3,3], 'fingers':[1,1,1,1]},
    'Dm7':   {'name':'Dm7',   'frets':[2,2,1,3], 'fingers':[1,2,0,3]},
    'Em7':   {'name':'Em7',   'frets':[0,2,0,2], 'fingers':[0,1,0,2]},
    'F#m7':  {'name':'F#m7',  'frets':[2,4,2,4], 'fingers':[1,3,1,4]},
    'Gm7':   {'name':'Gm7',   'frets':[0,2,1,1], 'fingers':[0,3,1,2]},
    'Cmaj7': {'name':'Cmaj7', 'frets':[0,0,0,2], 'fingers':[0,0,0,2]},
    'Fmaj7': {'name':'Fmaj7', 'frets':[2,4,1,3], 'fingers':[1,3,0,2]},
    'Gmaj7': {'name':'Gmaj7', 'frets':[0,2,2,2], 'fingers':[0,1,2,3]},
    'Dsus4': {'name':'Dsus4', 'frets':[2,2,0,0], 'fingers':[1,2,0,0]},
    'Dsus2': {'name':'Dsus2', 'frets':[2,2,0,0], 'fingers':[1,2,0,0]},
    'Asus4': {'name':'Asus4', 'frets':[2,2,0,0], 'fingers':[1,2,0,0]},
    'Gsus4': {'name':'Gsus4', 'frets':[0,2,3,3], 'fingers':[0,1,2,3]},
}

def chord(name):
    return CHORDS.get(name, {'name': name, 'frets': [0,0,0,0], 'fingers': [0,0,0,0]})

def make_id(title, artist):
    s = f"{title}-{artist}".lower()
    s = re.sub(r'[^a-z0-9]+', '-', s)
    return s.strip('-')

# Strumming patterns per level
EASY_STRUMS = [
    ("D D D D", "Simple all downstrums, 4 beats"),
    ("D D D D", "Steady downstrum pattern"),
    ("D - D -", "Down strum on beats 1 and 3"),
]
MED_STRUMS = [
    ("D D U U D U", "Island strum pattern"),
    ("D U D U D U", "Alternating down-up pattern"),
    ("D D U D U D", "Syncopated strum pattern"),
    ("D U x U D U", "Muted strum with chuck"),
]
ADV_STRUMS = [
    ("D D U U D U", "Island strum with emphasis"),
    ("D U x U D U", "Chunk strum with muted beat"),
    ("D U D U x U D U", "Complex syncopated pattern"),
    ("D x U U D U", "Percussive strum pattern"),
]

# Common chord progressions for songs
# (easy_chords, medium_chords, advanced_chords)
PROGRESSIONS = [
    # I-V-vi-IV in C
    (['C','G','Am','F'], ['C','G','Am','F','Em'], ['Cmaj7','G','Am7','Fmaj7','Em7']),
    # I-V-vi-IV in G
    (['G','D','Em','C'], ['G','D','Em','C','Am'], ['Gmaj7','D','Em7','Cmaj7','Am7']),
    # I-IV-V in C
    (['C','F','G'], ['C','F','G','Am'], ['Cmaj7','Fmaj7','G7','Am7']),
    # I-IV-V in G
    (['G','C','D'], ['G','C','D','Em'], ['Gmaj7','Cmaj7','D7','Em7']),
    # I-IV-V in D
    (['D','G','A'], ['D','G','A','Bm'], ['D','Gmaj7','A7','Bm7']),
    # vi-IV-I-V in C
    (['Am','F','C','G'], ['Am','F','C','G','Dm'], ['Am7','Fmaj7','Cmaj7','G7','Dm7']),
    # I-vi-IV-V in C
    (['C','Am','F','G'], ['C','Am','F','G','Em'], ['Cmaj7','Am7','Fmaj7','G7','Em7']),
    # Blues in A
    (['A','D','E'], ['A','D','E','A7'], ['A7','D7','E7','A']),
    # I-V-vi-IV in A
    (['A','E','F#m','D'], ['A','E','F#m','D','Bm'], ['A','E7','F#m7','D','Bm7']),
    # Minor i-iv-v
    (['Am','Dm','Em'], ['Am','Dm','Em','G'], ['Am7','Dm7','Em7','G7']),
    # I-IV in C
    (['C','F'], ['C','F','G'], ['Cmaj7','Fmaj7','G7']),
    # Pop punk
    (['G','D','Am','C'], ['G','D','Am','C','Em'], ['Gmaj7','D','Am7','Cmaj7','Em7']),
]

def make_lyrics(title, artist, chords):
    """Generate placeholder lyrics with chord markers."""
    c = chords
    n = len(c)
    lines = [
        f"[{c[0%n]}] Playing along to {title}",
        f"[{c[1%n]}] A song by {artist}",
        f"[{c[0%n]}] Strum the chords and [{ c[2%n] if n>2 else c[0%n]}] sing along",
        f"[{c[1%n]}] Feel the music [{ c[3%n] if n>3 else c[0%n]}] carry on",
        "",
        f"[{c[0%n]}] Verse two starts [{ c[1%n]}] here we go",
        f"[{c[2%n] if n>2 else c[0%n]}] Keep the rhythm [{ c[3%n] if n>3 else c[1%n]}] nice and slow",
        f"[{c[0%n]}] Bridge section [{ c[1%n]}] changing key",
        f"[{c[2%n] if n>2 else c[0%n]}] Back to the [{ c[0%n]}] melody",
        "",
        f"[{c[0%n]}] Final chorus [{ c[1%n]}] one more time",
        f"[{c[2%n] if n>2 else c[0%n]}] Ending on a [{ c[0%n]}] perfect rhyme",
    ]
    return "\n".join(lines)

# === SONG LIST (1000 popular songs with artist) ===
SONGS = [
    # Pop
    ("Shape of You", "Ed Sheeran"),
    ("Blinding Lights", "The Weeknd"),
    ("Someone Like You", "Adele"),
    ("Rolling in the Deep", "Adele"),
    ("Hello", "Adele"),
    ("Set Fire to the Rain", "Adele"),
    ("Easy on Me", "Adele"),
    ("Uptown Funk", "Bruno Mars"),
    ("Just the Way You Are", "Bruno Mars"),
    ("Grenade", "Bruno Mars"),
    ("Treasure", "Bruno Mars"),
    ("Count on Me", "Bruno Mars"),
    ("Locked Out of Heaven", "Bruno Mars"),
    ("When I Was Your Man", "Bruno Mars"),
    ("Thinking Out Loud", "Ed Sheeran"),
    ("Perfect", "Ed Sheeran"),
    ("Photograph", "Ed Sheeran"),
    ("Castle on the Hill", "Ed Sheeran"),
    ("Galway Girl", "Ed Sheeran"),
    ("Happier", "Ed Sheeran"),
    ("Bad Habits", "Ed Sheeran"),
    ("Shivers", "Ed Sheeran"),
    ("Shallow", "Lady Gaga"),
    ("Poker Face", "Lady Gaga"),
    ("Born This Way", "Lady Gaga"),
    ("Bad Romance", "Lady Gaga"),
    ("Stay", "Rihanna"),
    ("Umbrella", "Rihanna"),
    ("Diamonds", "Rihanna"),
    ("We Found Love", "Rihanna"),
    ("Love the Way You Lie", "Eminem"),
    ("Lose Yourself", "Eminem"),
    ("Roar", "Katy Perry"),
    ("Firework", "Katy Perry"),
    ("Dark Horse", "Katy Perry"),
    ("Teenage Dream", "Katy Perry"),
    ("Shake It Off", "Taylor Swift"),
    ("Love Story", "Taylor Swift"),
    ("You Belong with Me", "Taylor Swift"),
    ("Blank Space", "Taylor Swift"),
    ("Style", "Taylor Swift"),
    ("Wildest Dreams", "Taylor Swift"),
    ("Anti-Hero", "Taylor Swift"),
    ("Cardigan", "Taylor Swift"),
    ("All Too Well", "Taylor Swift"),
    ("Cruel Summer", "Taylor Swift"),
    ("Levitating", "Dua Lipa"),
    ("Don't Start Now", "Dua Lipa"),
    ("New Rules", "Dua Lipa"),
    ("Physical", "Dua Lipa"),
    # Rock
    ("Bohemian Rhapsody", "Queen"),
    ("We Will Rock You", "Queen"),
    ("Don't Stop Me Now", "Queen"),
    ("Somebody to Love", "Queen"),
    ("Radio Ga Ga", "Queen"),
    ("Under Pressure", "Queen"),
    ("Stairway to Heaven", "Led Zeppelin"),
    ("Whole Lotta Love", "Led Zeppelin"),
    ("Kashmir", "Led Zeppelin"),
    ("Hotel California", "Eagles"),
    ("Take It Easy", "Eagles"),
    ("Desperado", "Eagles"),
    ("Peaceful Easy Feeling", "Eagles"),
    ("Sweet Child O Mine", "Guns N Roses"),
    ("Paradise City", "Guns N Roses"),
    ("November Rain", "Guns N Roses"),
    ("Patience", "Guns N Roses"),
    ("Smells Like Teen Spirit", "Nirvana"),
    ("Come As You Are", "Nirvana"),
    ("Heart-Shaped Box", "Nirvana"),
    ("Lithium", "Nirvana"),
    ("In Bloom", "Nirvana"),
    ("Back in Black", "AC/DC"),
    ("Highway to Hell", "AC/DC"),
    ("Thunderstruck", "AC/DC"),
    ("You Shook Me All Night Long", "AC/DC"),
    ("Livin on a Prayer", "Bon Jovi"),
    ("Wanted Dead or Alive", "Bon Jovi"),
    ("Its My Life", "Bon Jovi"),
    ("Dream On", "Aerosmith"),
    ("Walk This Way", "Aerosmith"),
    ("I Don't Want to Miss a Thing", "Aerosmith"),
    ("Comfortably Numb", "Pink Floyd"),
    ("Wish You Were Here", "Pink Floyd"),
    ("Another Brick in the Wall", "Pink Floyd"),
    ("Money", "Pink Floyd"),
    ("Paint It Black", "Rolling Stones"),
    ("Satisfaction", "Rolling Stones"),
    ("Sympathy for the Devil", "Rolling Stones"),
    ("Wild Horses", "Rolling Stones"),
    ("Gimme Shelter", "Rolling Stones"),
    ("Born to Run", "Bruce Springsteen"),
    ("Dancing in the Dark", "Bruce Springsteen"),
    ("Thunder Road", "Bruce Springsteen"),
    ("Free Fallin", "Tom Petty"),
    ("American Girl", "Tom Petty"),
    ("I Won't Back Down", "Tom Petty"),
    ("Learning to Fly", "Tom Petty"),
    # Classic Rock / Folk Rock
    ("Blowin in the Wind", "Bob Dylan"),
    ("Knockin on Heavens Door", "Bob Dylan"),
    ("The Times They Are a Changin", "Bob Dylan"),
    ("Like a Rolling Stone", "Bob Dylan"),
    ("Mr Tambourine Man", "Bob Dylan"),
    ("Bridge Over Troubled Water", "Simon and Garfunkel"),
    ("The Sound of Silence", "Simon and Garfunkel"),
    ("Mrs Robinson", "Simon and Garfunkel"),
    ("Scarborough Fair", "Simon and Garfunkel"),
    ("The Boxer", "Simon and Garfunkel"),
    ("Fire and Rain", "James Taylor"),
    ("You've Got a Friend", "James Taylor"),
    ("Carolina in My Mind", "James Taylor"),
    ("American Pie", "Don McLean"),
    ("Vincent", "Don McLean"),
    ("Cat's in the Cradle", "Harry Chapin"),
    ("Behind Blue Eyes", "The Who"),
    ("Pinball Wizard", "The Who"),
    ("Won't Get Fooled Again", "The Who"),
    ("Born to Be Wild", "Steppenwolf"),
    ("Purple Haze", "Jimi Hendrix"),
    ("All Along the Watchtower", "Jimi Hendrix"),
    ("Hey Joe", "Jimi Hendrix"),
    ("The Wind Cries Mary", "Jimi Hendrix"),
    ("Sunshine of Your Love", "Cream"),
    ("White Room", "Cream"),
    ("Layla", "Eric Clapton"),
    ("Tears in Heaven", "Eric Clapton"),
    ("Wonderful Tonight", "Eric Clapton"),
    ("Cocaine", "Eric Clapton"),
    # Beatles
    ("Yesterday", "The Beatles"),
    ("Here Comes the Sun", "The Beatles"),
    ("Come Together", "The Beatles"),
    ("Let It Be", "The Beatles"),
    ("Hey Jude", "The Beatles"),
    ("Blackbird", "The Beatles"),
    ("While My Guitar Gently Weeps", "The Beatles"),
    ("In My Life", "The Beatles"),
    ("Norwegian Wood", "The Beatles"),
    ("Something", "The Beatles"),
    ("Across the Universe", "The Beatles"),
    ("Twist and Shout", "The Beatles"),
    ("I Want to Hold Your Hand", "The Beatles"),
    ("All You Need Is Love", "The Beatles"),
    ("Strawberry Fields Forever", "The Beatles"),
    ("Eleanor Rigby", "The Beatles"),
    ("A Day in the Life", "The Beatles"),
    ("Help", "The Beatles"),
    ("Penny Lane", "The Beatles"),
    ("Get Back", "The Beatles"),
    ("Don't Let Me Down", "The Beatles"),
    ("Love Me Do", "The Beatles"),
    ("Michelle", "The Beatles"),
    # 90s/2000s Rock
    ("Wonderwall", "Oasis"),
    ("Don't Look Back in Anger", "Oasis"),
    ("Champagne Supernova", "Oasis"),
    ("Live Forever", "Oasis"),
    ("Losing My Religion", "R.E.M."),
    ("Everybody Hurts", "R.E.M."),
    ("Shiny Happy People", "R.E.M."),
    ("Man on the Moon", "R.E.M."),
    ("Under the Bridge", "Red Hot Chili Peppers"),
    ("Californication", "Red Hot Chili Peppers"),
    ("Scar Tissue", "Red Hot Chili Peppers"),
    ("Snow Hey Oh", "Red Hot Chili Peppers"),
    ("Otherside", "Red Hot Chili Peppers"),
    ("Black", "Pearl Jam"),
    ("Alive", "Pearl Jam"),
    ("Jeremy", "Pearl Jam"),
    ("Even Flow", "Pearl Jam"),
    ("Yellow Ledbetter", "Pearl Jam"),
    ("Plush", "Stone Temple Pilots"),
    ("Interstate Love Song", "Stone Temple Pilots"),
    ("Creep", "Radiohead"),
    ("Karma Police", "Radiohead"),
    ("No Surprises", "Radiohead"),
    ("High and Dry", "Radiohead"),
    ("Zombie", "The Cranberries"),
    ("Linger", "The Cranberries"),
    ("Dreams", "The Cranberries"),
    ("Mr Jones", "Counting Crows"),
    ("Round Here", "Counting Crows"),
    # Indie / Alt
    ("Hey Ya", "Outkast"),
    ("Somebody That I Used to Know", "Gotye"),
    ("Pumped Up Kicks", "Foster the People"),
    ("Take Me Out", "Franz Ferdinand"),
    ("Chasing Cars", "Snow Patrol"),
    ("Run", "Snow Patrol"),
    ("Yellow", "Coldplay"),
    ("The Scientist", "Coldplay"),
    ("Fix You", "Coldplay"),
    ("Clocks", "Coldplay"),
    ("Viva la Vida", "Coldplay"),
    ("A Sky Full of Stars", "Coldplay"),
    ("Speed of Sound", "Coldplay"),
    ("Paradise", "Coldplay"),
    ("In My Place", "Coldplay"),
    ("The Hardest Part", "Coldplay"),
    ("Bitter Sweet Symphony", "The Verve"),
    ("Iris", "Goo Goo Dolls"),
    ("Slide", "Goo Goo Dolls"),
    ("Name", "Goo Goo Dolls"),
    ("Torn", "Natalie Imbruglia"),
    ("Closing Time", "Semisonic"),
    ("Semi-Charmed Life", "Third Eye Blind"),
    ("Jumper", "Third Eye Blind"),
    ("1979", "Smashing Pumpkins"),
    ("Tonight Tonight", "Smashing Pumpkins"),
    ("Disarm", "Smashing Pumpkins"),
    ("Bullet with Butterfly Wings", "Smashing Pumpkins"),
    ("Glycerine", "Bush"),
    ("Crash into Me", "Dave Matthews Band"),
    ("Ants Marching", "Dave Matthews Band"),
    ("Satellite", "Dave Matthews Band"),
    ("Two Step", "Dave Matthews Band"),
    # Country
    ("Jolene", "Dolly Parton"),
    ("9 to 5", "Dolly Parton"),
    ("I Will Always Love You", "Dolly Parton"),
    ("Ring of Fire", "Johnny Cash"),
    ("Folsom Prison Blues", "Johnny Cash"),
    ("Walk the Line", "Johnny Cash"),
    ("Hurt", "Johnny Cash"),
    ("Man in Black", "Johnny Cash"),
    ("Friends in Low Places", "Garth Brooks"),
    ("The Dance", "Garth Brooks"),
    ("Thunder Rolls", "Garth Brooks"),
    ("Wagon Wheel", "Old Crow Medicine Show"),
    ("The Gambler", "Kenny Rogers"),
    ("Islands in the Stream", "Kenny Rogers"),
    ("On the Road Again", "Willie Nelson"),
    ("Blue Eyes Crying in the Rain", "Willie Nelson"),
    ("Always on My Mind", "Willie Nelson"),
    ("Mammas Don't Let Your Babies Grow Up", "Willie Nelson"),
    ("He Stopped Loving Her Today", "George Jones"),
    ("Achy Breaky Heart", "Billy Ray Cyrus"),
    ("Boot Scootin Boogie", "Brooks and Dunn"),
    ("Cruise", "Florida Georgia Line"),
    ("Chicken Fried", "Zac Brown Band"),
    ("Toes", "Zac Brown Band"),
    ("Colder Weather", "Zac Brown Band"),
    ("Tennessee Whiskey", "Chris Stapleton"),
    ("Traveller", "Chris Stapleton"),
    ("Body Like a Back Road", "Sam Hunt"),
    ("Die a Happy Man", "Thomas Rhett"),
    ("Meant to Be", "Bebe Rexha ft Florida Georgia Line"),
    ("Need You Now", "Lady A"),
    ("Wanted", "Hunter Hayes"),
    ("Springsteen", "Eric Church"),
    ("Drunk on a Plane", "Dierks Bentley"),
    ("Drunk on You", "Luke Bryan"),
    ("Play It Again", "Luke Bryan"),
    ("Dirt Road Anthem", "Jason Aldean"),
    ("Amazed", "Lonestar"),
    ("Breathe", "Faith Hill"),
    ("Before He Cheats", "Carrie Underwood"),
    ("Jesus Take the Wheel", "Carrie Underwood"),
    ("Humble and Kind", "Tim McGraw"),
    ("Live Like You Were Dying", "Tim McGraw"),
    # R&B / Soul
    ("Ain't No Sunshine", "Bill Withers"),
    ("Lean on Me", "Bill Withers"),
    ("Use Me", "Bill Withers"),
    ("Lovely Day", "Bill Withers"),
    ("Just My Imagination", "The Temptations"),
    ("My Girl", "The Temptations"),
    ("I Heard It Through the Grapevine", "Marvin Gaye"),
    ("Lets Get It On", "Marvin Gaye"),
    ("What's Going On", "Marvin Gaye"),
    ("Sexual Healing", "Marvin Gaye"),
    ("Superstition", "Stevie Wonder"),
    ("Isn't She Lovely", "Stevie Wonder"),
    ("I Just Called to Say I Love You", "Stevie Wonder"),
    ("Sir Duke", "Stevie Wonder"),
    ("Signed Sealed Delivered", "Stevie Wonder"),
    ("A Change Is Gonna Come", "Sam Cooke"),
    ("Wonderful World", "Sam Cooke"),
    ("Respect", "Aretha Franklin"),
    ("Natural Woman", "Aretha Franklin"),
    ("I Say a Little Prayer", "Aretha Franklin"),
    ("Think", "Aretha Franklin"),
    ("Sittin on the Dock of the Bay", "Otis Redding"),
    ("Try a Little Tenderness", "Otis Redding"),
    ("Stand by Me", "Ben E. King"),
    ("Georgia on My Mind", "Ray Charles"),
    ("Hit the Road Jack", "Ray Charles"),
    ("I Got You Babe", "Sonny and Cher"),
    ("How Sweet It Is", "James Taylor"),
    ("Unchained Melody", "Righteous Brothers"),
    ("Put Your Head on My Shoulder", "Paul Anka"),
    ("At Last", "Etta James"),
    ("I'd Rather Go Blind", "Etta James"),
    # Modern R&B
    ("No One", "Alicia Keys"),
    ("If I Ain't Got You", "Alicia Keys"),
    ("Fallin", "Alicia Keys"),
    ("Girl on Fire", "Alicia Keys"),
    ("Halo", "Beyonce"),
    ("Crazy in Love", "Beyonce"),
    ("Irreplaceable", "Beyonce"),
    ("Single Ladies", "Beyonce"),
    ("Love on Top", "Beyonce"),
    ("All of Me", "John Legend"),
    ("Ordinary People", "John Legend"),
    ("Stay with Me", "Sam Smith"),
    ("Too Good at Goodbyes", "Sam Smith"),
    ("Lay Me Down", "Sam Smith"),
    ("Thinking Bout You", "Frank Ocean"),
    ("Nights", "Frank Ocean"),
    ("Redbone", "Childish Gambino"),
    ("Blinding Lights", "The Weeknd"),
    ("Can't Feel My Face", "The Weeknd"),
    ("Starboy", "The Weeknd"),
    ("Save Your Tears", "The Weeknd"),
    ("Die for You", "The Weeknd"),
    # Folk / Singer-Songwriter
    ("Fast Car", "Tracy Chapman"),
    ("Talkin Bout a Revolution", "Tracy Chapman"),
    ("Big Yellow Taxi", "Joni Mitchell"),
    ("Both Sides Now", "Joni Mitchell"),
    ("A Case of You", "Joni Mitchell"),
    ("River", "Joni Mitchell"),
    ("Landslide", "Fleetwood Mac"),
    ("Dreams", "Fleetwood Mac"),
    ("Go Your Own Way", "Fleetwood Mac"),
    ("The Chain", "Fleetwood Mac"),
    ("Everywhere", "Fleetwood Mac"),
    ("Rhiannon", "Fleetwood Mac"),
    ("Little Lies", "Fleetwood Mac"),
    ("Don't Stop", "Fleetwood Mac"),
    ("Songbird", "Fleetwood Mac"),
    ("Dust in the Wind", "Kansas"),
    ("Carry on Wayward Son", "Kansas"),
    ("More Than a Feeling", "Boston"),
    ("Peace of Mind", "Boston"),
    ("Africa", "Toto"),
    ("Rosanna", "Toto"),
    ("Hold the Line", "Toto"),
    ("Don't Stop Believin", "Journey"),
    ("Open Arms", "Journey"),
    ("Faithfully", "Journey"),
    ("Lights", "Journey"),
    ("Separate Ways", "Journey"),
    ("Any Way You Want It", "Journey"),
    ("Here I Go Again", "Whitesnake"),
    ("Every Rose Has Its Thorn", "Poison"),
    ("Home Sweet Home", "Motley Crue"),
    ("Sister Christian", "Night Ranger"),
    ("Every Breath You Take", "The Police"),
    ("Roxanne", "The Police"),
    ("Message in a Bottle", "The Police"),
    ("Don't Stand So Close to Me", "The Police"),
    ("Walking on the Moon", "The Police"),
    ("With or Without You", "U2"),
    ("One", "U2"),
    ("Where the Streets Have No Name", "U2"),
    ("Beautiful Day", "U2"),
    ("I Still Haven't Found", "U2"),
    ("Sunday Bloody Sunday", "U2"),
    ("Pride", "U2"),
    # Reggae / Ska
    ("No Woman No Cry", "Bob Marley"),
    ("Three Little Birds", "Bob Marley"),
    ("Redemption Song", "Bob Marley"),
    ("Buffalo Soldier", "Bob Marley"),
    ("Is This Love", "Bob Marley"),
    ("Jamming", "Bob Marley"),
    ("Get Up Stand Up", "Bob Marley"),
    ("One Love", "Bob Marley"),
    ("Stir It Up", "Bob Marley"),
    ("Could You Be Loved", "Bob Marley"),
    ("Waiting in Vain", "Bob Marley"),
    ("I Shot the Sheriff", "Bob Marley"),
    ("Red Red Wine", "UB40"),
    ("Kingston Town", "UB40"),
    ("Santeria", "Sublime"),
    ("What I Got", "Sublime"),
    ("Wrong Way", "Sublime"),
    ("Badfish", "Sublime"),
    # Jazz Standards
    ("Fly Me to the Moon", "Frank Sinatra"),
    ("My Way", "Frank Sinatra"),
    ("New York New York", "Frank Sinatra"),
    ("The Way You Look Tonight", "Frank Sinatra"),
    ("Come Fly with Me", "Frank Sinatra"),
    ("That's Life", "Frank Sinatra"),
    ("I've Got You Under My Skin", "Frank Sinatra"),
    ("Moon River", "Andy Williams"),
    ("What a Wonderful World", "Louis Armstrong"),
    ("Dream a Little Dream of Me", "Mama Cass"),
    ("Summertime", "George Gershwin"),
    ("Autumn Leaves", "Nat King Cole"),
    ("Unforgettable", "Nat King Cole"),
    ("L-O-V-E", "Nat King Cole"),
    ("The Girl from Ipanema", "Stan Getz"),
    ("Take Five", "Dave Brubeck"),
    ("Feeling Good", "Nina Simone"),
    ("My Baby Just Cares for Me", "Nina Simone"),
    ("Sinnerman", "Nina Simone"),
    ("Blue Moon", "Rodgers and Hart"),
    ("Cheek to Cheek", "Fred Astaire"),
    ("Beyond the Sea", "Bobby Darin"),
    ("Mack the Knife", "Bobby Darin"),
    ("Splish Splash", "Bobby Darin"),
    # 80s Pop
    ("Take on Me", "A-ha"),
    ("Every Little Thing She Does Is Magic", "The Police"),
    ("Careless Whisper", "George Michael"),
    ("Faith", "George Michael"),
    ("Last Christmas", "Wham"),
    ("Wake Me Up Before You Go Go", "Wham"),
    ("Girls Just Want to Have Fun", "Cyndi Lauper"),
    ("Time After Time", "Cyndi Lauper"),
    ("True Colors", "Cyndi Lauper"),
    ("Like a Prayer", "Madonna"),
    ("Material Girl", "Madonna"),
    ("Papa Don't Preach", "Madonna"),
    ("La Isla Bonita", "Madonna"),
    ("I Wanna Dance with Somebody", "Whitney Houston"),
    ("Greatest Love of All", "Whitney Houston"),
    ("How Will I Know", "Whitney Houston"),
    ("I Will Always Love You", "Whitney Houston"),
    ("Saving All My Love for You", "Whitney Houston"),
    ("Billie Jean", "Michael Jackson"),
    ("Beat It", "Michael Jackson"),
    ("Thriller", "Michael Jackson"),
    ("Man in the Mirror", "Michael Jackson"),
    ("The Way You Make Me Feel", "Michael Jackson"),
    ("Black or White", "Michael Jackson"),
    ("Don't You Forget About Me", "Simple Minds"),
    ("Everybody Wants to Rule the World", "Tears for Fears"),
    ("Shout", "Tears for Fears"),
    ("Mad World", "Tears for Fears"),
    ("Tainted Love", "Soft Cell"),
    ("Sweet Dreams", "Eurythmics"),
    ("Here Comes the Rain Again", "Eurythmics"),
    ("Just Like Heaven", "The Cure"),
    ("Boys Don't Cry", "The Cure"),
    ("Friday I'm in Love", "The Cure"),
    ("Lovesong", "The Cure"),
    ("Blue Monday", "New Order"),
    ("Love Will Tear Us Apart", "Joy Division"),
    ("There Is a Light That Never Goes Out", "The Smiths"),
    ("How Soon Is Now", "The Smiths"),
    ("This Charming Man", "The Smiths"),
    ("Personal Jesus", "Depeche Mode"),
    ("Enjoy the Silence", "Depeche Mode"),
    ("Never Gonna Give You Up", "Rick Astley"),
    ("Together Forever", "Rick Astley"),
    ("Don't Stop Believin", "Journey"),
    ("Jessie's Girl", "Rick Springfield"),
    ("Come On Eileen", "Dexys Midnight Runners"),
    ("I Melt with You", "Modern English"),
    ("867-5309 Jenny", "Tommy Tutone"),
    # 90s Pop
    ("Waterfalls", "TLC"),
    ("No Scrubs", "TLC"),
    ("MMMBop", "Hanson"),
    ("Tubthumping", "Chumbawamba"),
    ("Wannabe", "Spice Girls"),
    ("Say You'll Be There", "Spice Girls"),
    ("...Baby One More Time", "Britney Spears"),
    ("Oops I Did It Again", "Britney Spears"),
    ("Toxic", "Britney Spears"),
    ("Genie in a Bottle", "Christina Aguilera"),
    ("Beautiful", "Christina Aguilera"),
    ("I Want It That Way", "Backstreet Boys"),
    ("Everybody", "Backstreet Boys"),
    ("As Long as You Love Me", "Backstreet Boys"),
    ("Bye Bye Bye", "NSYNC"),
    ("Tearin Up My Heart", "NSYNC"),
    ("It's Gonna Be Me", "NSYNC"),
    ("Lovefool", "The Cardigans"),
    ("Kiss Me", "Sixpence None the Richer"),
    ("Smooth", "Santana ft Rob Thomas"),
    ("Maria Maria", "Santana"),
    ("Steal My Sunshine", "Len"),
    ("All Star", "Smash Mouth"),
    ("Walking on the Sun", "Smash Mouth"),
    ("Fly", "Sugar Ray"),
    ("Every Morning", "Sugar Ray"),
    ("Save Tonight", "Eagle-Eye Cherry"),
    ("Inside Out", "Eve 6"),
    ("Breakfast at Tiffanys", "Deep Blue Something"),
    ("Good Riddance", "Green Day"),
    ("Basket Case", "Green Day"),
    ("When I Come Around", "Green Day"),
    ("Boulevard of Broken Dreams", "Green Day"),
    ("Holiday", "Green Day"),
    ("21 Guns", "Green Day"),
    ("American Idiot", "Green Day"),
    # 2000s
    ("Clint Eastwood", "Gorillaz"),
    ("Feel Good Inc", "Gorillaz"),
    ("Crazy", "Gnarls Barkley"),
    ("Seven Nation Army", "The White Stripes"),
    ("Naive", "The Kooks"),
    ("Seaside", "The Kooks"),
    ("Chelsea Dagger", "The Fratellis"),
    ("Sex on Fire", "Kings of Leon"),
    ("Use Somebody", "Kings of Leon"),
    ("Apologize", "OneRepublic"),
    ("Counting Stars", "OneRepublic"),
    ("Stop and Stare", "OneRepublic"),
    ("Secrets", "OneRepublic"),
    ("I Gotta Feeling", "Black Eyed Peas"),
    ("Where Is the Love", "Black Eyed Peas"),
    ("Hey There Delilah", "Plain White T's"),
    ("1234", "Plain White T's"),
    ("How to Save a Life", "The Fray"),
    ("Over My Head", "The Fray"),
    ("You Found Me", "The Fray"),
    ("Hemorrhage", "Fuel"),
    ("Kryptonite", "3 Doors Down"),
    ("Here Without You", "3 Doors Down"),
    ("It's Been Awhile", "Staind"),
    ("Outside", "Staind"),
    ("Drive", "Incubus"),
    ("Wish You Were Here", "Incubus"),
    ("Mr Brightside", "The Killers"),
    ("Somebody Told Me", "The Killers"),
    ("Human", "The Killers"),
    ("When You Were Young", "The Killers"),
    ("Smile Like You Mean It", "The Killers"),
    ("All the Small Things", "Blink-182"),
    ("I Miss You", "Blink-182"),
    ("What's My Age Again", "Blink-182"),
    ("Dammit", "Blink-182"),
    ("Adam's Song", "Blink-182"),
    ("The Rock Show", "Blink-182"),
    ("First Date", "Blink-182"),
    ("Ocean Avenue", "Yellowcard"),
    ("The Middle", "Jimmy Eat World"),
    ("Sweetness", "Jimmy Eat World"),
    ("Sugar We're Goin Down", "Fall Out Boy"),
    ("Thnks fr th Mmrs", "Fall Out Boy"),
    ("Dance Dance", "Fall Out Boy"),
    ("Uma Thurman", "Fall Out Boy"),
    ("Centuries", "Fall Out Boy"),
    ("Misery Business", "Paramore"),
    ("Decode", "Paramore"),
    ("The Only Exception", "Paramore"),
    ("Still Into You", "Paramore"),
    ("Welcome to the Black Parade", "My Chemical Romance"),
    ("Helena", "My Chemical Romance"),
    ("I'm Not Okay", "My Chemical Romance"),
    ("Teenagers", "My Chemical Romance"),
    ("Famous Last Words", "My Chemical Romance"),
    ("In the End", "Linkin Park"),
    ("Numb", "Linkin Park"),
    ("Crawling", "Linkin Park"),
    ("Breaking the Habit", "Linkin Park"),
    ("What I've Done", "Linkin Park"),
    ("Somewhere I Belong", "Linkin Park"),
    ("New Divide", "Linkin Park"),
    ("Faint", "Linkin Park"),
    ("One Step Closer", "Linkin Park"),
    ("Leave Out All the Rest", "Linkin Park"),
    # 2010s Pop
    ("Royals", "Lorde"),
    ("Team", "Lorde"),
    ("Green Light", "Lorde"),
    ("Somebody Else", "The 1975"),
    ("Chocolate", "The 1975"),
    ("The Sound", "The 1975"),
    ("Robbers", "The 1975"),
    ("Stitches", "Shawn Mendes"),
    ("Treat You Better", "Shawn Mendes"),
    ("There's Nothing Holdin Me Back", "Shawn Mendes"),
    ("In My Blood", "Shawn Mendes"),
    ("Mercy", "Shawn Mendes"),
    ("Senorita", "Shawn Mendes"),
    ("Sorry", "Justin Bieber"),
    ("Love Yourself", "Justin Bieber"),
    ("What Do You Mean", "Justin Bieber"),
    ("Baby", "Justin Bieber"),
    ("Peaches", "Justin Bieber"),
    ("Ghost", "Justin Bieber"),
    ("Stay", "Justin Bieber"),
    ("Intentions", "Justin Bieber"),
    ("Watermelon Sugar", "Harry Styles"),
    ("Adore You", "Harry Styles"),
    ("Sign of the Times", "Harry Styles"),
    ("Falling", "Harry Styles"),
    ("As It Was", "Harry Styles"),
    ("Golden", "Harry Styles"),
    ("Late Night Talking", "Harry Styles"),
    ("Kiwi", "Harry Styles"),
    ("Drivers License", "Olivia Rodrigo"),
    ("Good 4 U", "Olivia Rodrigo"),
    ("Deja Vu", "Olivia Rodrigo"),
    ("Traitor", "Olivia Rodrigo"),
    ("Brutal", "Olivia Rodrigo"),
    ("Happier", "Olivia Rodrigo"),
    ("Vampire", "Olivia Rodrigo"),
    ("Get Lucky", "Daft Punk"),
    ("Instant Crush", "Daft Punk"),
    ("Around the World", "Daft Punk"),
    ("One More Time", "Daft Punk"),
    ("Harder Better Faster Stronger", "Daft Punk"),
    ("Radioactive", "Imagine Dragons"),
    ("Demons", "Imagine Dragons"),
    ("Believer", "Imagine Dragons"),
    ("Thunder", "Imagine Dragons"),
    ("Whatever It Takes", "Imagine Dragons"),
    ("On Top of the World", "Imagine Dragons"),
    ("Natural", "Imagine Dragons"),
    ("Bones", "Imagine Dragons"),
    ("Enemy", "Imagine Dragons"),
    ("Sail", "AWOLNATION"),
    ("Pompeii", "Bastille"),
    ("Happier", "Bastille"),
    ("Take Me to Church", "Hozier"),
    ("Someone New", "Hozier"),
    ("Cherry Wine", "Hozier"),
    ("From Eden", "Hozier"),
    ("Too Sweet", "Hozier"),
    ("Budapest", "George Ezra"),
    ("Shotgun", "George Ezra"),
    ("Blame It on Me", "George Ezra"),
    ("Ho Hey", "Lumineers"),
    ("Stubborn Love", "Lumineers"),
    ("Ophelia", "Lumineers"),
    ("Sleep on the Floor", "Lumineers"),
    ("Cleopatra", "Lumineers"),
    ("Home", "Edward Sharpe"),
    ("Little Talks", "Of Monsters and Men"),
    ("Dirty Paws", "Of Monsters and Men"),
    ("I of the Storm", "Of Monsters and Men"),
    ("Riptide", "Vance Joy"),
    ("Georgia", "Vance Joy"),
    ("Fire and the Flood", "Vance Joy"),
    ("Missing Piece", "Vance Joy"),
    ("Skinny Love", "Bon Iver"),
    ("Holocene", "Bon Iver"),
    ("Re Stacks", "Bon Iver"),
    ("Flume", "Bon Iver"),
    # Latin / International
    ("Despacito", "Luis Fonsi"),
    ("Bailando", "Enrique Iglesias"),
    ("Hero", "Enrique Iglesias"),
    ("Livin la Vida Loca", "Ricky Martin"),
    ("She Bangs", "Ricky Martin"),
    ("Hips Don't Lie", "Shakira"),
    ("Whenever Wherever", "Shakira"),
    ("Waka Waka", "Shakira"),
    ("La Bamba", "Ritchie Valens"),
    ("Guantanamera", "Traditional"),
    ("Besame Mucho", "Consuelo Velazquez"),
    ("Cielito Lindo", "Traditional"),
    ("Chan Chan", "Buena Vista Social Club"),
    ("Mas Que Nada", "Sergio Mendes"),
    ("Ai Se Eu Te Pego", "Michel Telo"),
    ("Danza Kuduro", "Don Omar"),
    ("Havana", "Camila Cabello"),
    ("Senorita", "Camila Cabello"),
    ("Bam Bam", "Camila Cabello"),
    ("Bad Bunny MIA", "Bad Bunny"),
    # Hawaiian / Island
    ("Somewhere Over the Rainbow", "Israel Kamakawiwoole"),
    ("White Sandy Beach", "Israel Kamakawiwoole"),
    ("Henehene Kou Aka", "Traditional Hawaiian"),
    ("Aloha Oe", "Queen Liliuokalani"),
    ("Pearly Shells", "Don Ho"),
    ("Tiny Bubbles", "Don Ho"),
    ("Hawaiian Roller Coaster Ride", "Disney"),
    ("Lava", "Disney"),
    # Musical Theatre
    ("Somewhere Over the Rainbow", "Wizard of Oz"),
    ("My Favorite Things", "Sound of Music"),
    ("Do Re Mi", "Sound of Music"),
    ("Edelweiss", "Sound of Music"),
    ("Memory", "Cats"),
    ("Defying Gravity", "Wicked"),
    ("Popular", "Wicked"),
    ("For Good", "Wicked"),
    ("One Day More", "Les Miserables"),
    ("I Dreamed a Dream", "Les Miserables"),
    ("On My Own", "Les Miserables"),
    ("Castle on a Cloud", "Les Miserables"),
    ("Tomorrow", "Annie"),
    ("Maybe", "Annie"),
    ("Seasons of Love", "Rent"),
    ("La Vie Boheme", "Rent"),
    ("Out Tonight", "Rent"),
    ("My Shot", "Hamilton"),
    ("Wait for It", "Hamilton"),
    ("Satisfied", "Hamilton"),
    ("The Schuyler Sisters", "Hamilton"),
    ("You'll Be Back", "Hamilton"),
    ("Dear Theodosia", "Hamilton"),
    ("Burn", "Hamilton"),
    ("It's Quiet Uptown", "Hamilton"),
    ("Helpless", "Hamilton"),
    ("Non-Stop", "Hamilton"),
    ("Alexander Hamilton", "Hamilton"),
    ("The Room Where It Happens", "Hamilton"),
    ("What'd I Miss", "Hamilton"),
    # Disney
    ("Let It Go", "Frozen"),
    ("Do You Want to Build a Snowman", "Frozen"),
    ("Into the Unknown", "Frozen 2"),
    ("Show Yourself", "Frozen 2"),
    ("A Whole New World", "Aladdin"),
    ("Friend Like Me", "Aladdin"),
    ("Prince Ali", "Aladdin"),
    ("Arabian Nights", "Aladdin"),
    ("Under the Sea", "Little Mermaid"),
    ("Part of Your World", "Little Mermaid"),
    ("Kiss the Girl", "Little Mermaid"),
    ("Circle of Life", "Lion King"),
    ("Hakuna Matata", "Lion King"),
    ("Can You Feel the Love Tonight", "Lion King"),
    ("I Just Can't Wait to Be King", "Lion King"),
    ("Be Our Guest", "Beauty and the Beast"),
    ("Tale as Old as Time", "Beauty and the Beast"),
    ("Beauty and the Beast", "Beauty and the Beast"),
    ("Colors of the Wind", "Pocahontas"),
    ("Just Around the Riverbend", "Pocahontas"),
    ("Go the Distance", "Hercules"),
    ("I Won't Say I'm in Love", "Hercules"),
    ("You'll Be in My Heart", "Tarzan"),
    ("Reflection", "Mulan"),
    ("I'll Make a Man Out of You", "Mulan"),
    ("When She Loved Me", "Toy Story 2"),
    ("You've Got a Friend in Me", "Toy Story"),
    ("Remember Me", "Coco"),
    ("Un Poco Loco", "Coco"),
    ("How Far I'll Go", "Moana"),
    ("You're Welcome", "Moana"),
    ("Shiny", "Moana"),
    ("We Don't Talk About Bruno", "Encanto"),
    ("Surface Pressure", "Encanto"),
    ("What Else Can I Do", "Encanto"),
    ("Waiting on a Miracle", "Encanto"),
    ("Married Life", "Up"),
    ("Speechless", "Aladdin 2019"),
    ("Try Everything", "Zootopia"),
    ("Almost There", "Princess and the Frog"),
    # Modern Alternative / Indie
    ("Electric Feel", "MGMT"),
    ("Kids", "MGMT"),
    ("Time to Pretend", "MGMT"),
    ("Do I Wanna Know", "Arctic Monkeys"),
    ("R U Mine", "Arctic Monkeys"),
    ("505", "Arctic Monkeys"),
    ("I Wanna Be Yours", "Arctic Monkeys"),
    ("Why'd You Only Call Me When You're High", "Arctic Monkeys"),
    ("Fluorescent Adolescent", "Arctic Monkeys"),
    ("I Bet You Look Good on the Dancefloor", "Arctic Monkeys"),
    ("Mardy Bum", "Arctic Monkeys"),
    ("Snap Out of It", "Arctic Monkeys"),
    ("Knee Socks", "Arctic Monkeys"),
    ("Sweater Weather", "The Neighbourhood"),
    ("Afraid", "The Neighbourhood"),
    ("Reflections", "The Neighbourhood"),
    ("Let Her Go", "Passenger"),
    ("Hearts on Fire", "Passenger"),
    ("Riptide", "Vance Joy"),
    ("Mess Is Mine", "Vance Joy"),
    ("Saturday Sun", "Vance Joy"),
    ("Rude", "MAGIC!"),
    ("Cheerleader", "OMI"),
    ("Stolen Dance", "Milky Chance"),
    ("Flashed Junk Mind", "Milky Chance"),
    ("Down Under", "Men at Work"),
    ("Sunday Morning", "Maroon 5"),
    ("She Will Be Loved", "Maroon 5"),
    ("This Love", "Maroon 5"),
    ("Moves Like Jagger", "Maroon 5"),
    ("Payphone", "Maroon 5"),
    ("Sugar", "Maroon 5"),
    ("Maps", "Maroon 5"),
    ("Girls Like You", "Maroon 5"),
    ("Memories", "Maroon 5"),
    ("Animals", "Maroon 5"),
    # More Modern Pop
    ("Closer", "Chainsmokers"),
    ("Roses", "Chainsmokers"),
    ("Don't Let Me Down", "Chainsmokers"),
    ("Something Just Like This", "Chainsmokers"),
    ("Paris", "Chainsmokers"),
    ("Wake Me Up", "Avicii"),
    ("Levels", "Avicii"),
    ("Hey Brother", "Avicii"),
    ("Waiting for Love", "Avicii"),
    ("The Nights", "Avicii"),
    ("Lean On", "Major Lazer"),
    ("Cold Water", "Major Lazer"),
    ("Cheap Thrills", "Sia"),
    ("Chandelier", "Sia"),
    ("Elastic Heart", "Sia"),
    ("Titanium", "David Guetta"),
    ("Flames", "David Guetta"),
    ("Without You", "David Guetta"),
    ("Rather Be", "Clean Bandit"),
    ("Rockabye", "Clean Bandit"),
    ("Solo", "Clean Bandit"),
    ("Symphony", "Clean Bandit"),
    ("Tongue Tied", "Grouplove"),
    ("Ways to Go", "Grouplove"),
    ("Colours", "Grouplove"),
    ("Dog Days Are Over", "Florence and the Machine"),
    ("Shake It Out", "Florence and the Machine"),
    ("You've Got the Love", "Florence and the Machine"),
    ("Cosmic Love", "Florence and the Machine"),
    ("Hunger", "Florence and the Machine"),
    # Classic Folk / Acoustic
    ("Scarborough Fair", "Traditional"),
    ("Greensleeves", "Traditional"),
    ("House of the Rising Sun", "Traditional"),
    ("Danny Boy", "Traditional"),
    ("Amazing Grace", "Traditional"),
    ("Will the Circle Be Unbroken", "Traditional"),
    ("This Land Is Your Land", "Woody Guthrie"),
    ("If I Had a Hammer", "Pete Seeger"),
    ("Turn Turn Turn", "The Byrds"),
    ("Mr Tambourine Man", "The Byrds"),
    ("The Sounds of Silence", "Simon and Garfunkel"),
    ("Homeward Bound", "Simon and Garfunkel"),
    ("Cecilia", "Simon and Garfunkel"),
    ("El Condor Pasa", "Simon and Garfunkel"),
    ("Puff the Magic Dragon", "Peter Paul and Mary"),
    ("Leaving on a Jet Plane", "Peter Paul and Mary"),
    ("Blowin in the Wind", "Peter Paul and Mary"),
    ("Where Have All the Flowers Gone", "Pete Seeger"),
    ("We Shall Overcome", "Traditional"),
    ("Kumbaya", "Traditional"),
    ("Swing Low Sweet Chariot", "Traditional"),
    ("Oh Susanna", "Stephen Foster"),
    ("Home on the Range", "Traditional"),
    ("Shenandoah", "Traditional"),
    ("Down by the Riverside", "Traditional"),
    ("When the Saints Go Marching In", "Traditional"),
    ("This Little Light of Mine", "Traditional"),
    ("He's Got the Whole World", "Traditional"),
    ("Simple Gifts", "Traditional"),
    # More 2020s Pop
    ("Blinding Lights", "The Weeknd"),
    ("Positions", "Ariana Grande"),
    ("7 Rings", "Ariana Grande"),
    ("Thank U Next", "Ariana Grande"),
    ("No Tears Left to Cry", "Ariana Grande"),
    ("Into You", "Ariana Grande"),
    ("Problem", "Ariana Grande"),
    ("Break Free", "Ariana Grande"),
    ("Side to Side", "Ariana Grande"),
    ("One Last Time", "Ariana Grande"),
    ("Rain on Me", "Lady Gaga"),
    ("Stupid Love", "Lady Gaga"),
    ("Flowers", "Miley Cyrus"),
    ("Wrecking Ball", "Miley Cyrus"),
    ("The Climb", "Miley Cyrus"),
    ("Party in the USA", "Miley Cyrus"),
    ("Malibu", "Miley Cyrus"),
    ("Midnight Sky", "Miley Cyrus"),
    ("We Can't Stop", "Miley Cyrus"),
    ("Happy", "Pharrell Williams"),
    ("Get Lucky", "Daft Punk"),
    ("Uptown Funk", "Mark Ronson"),
    ("Valerie", "Mark Ronson"),
    ("Rehab", "Amy Winehouse"),
    ("Back to Black", "Amy Winehouse"),
    ("Valerie", "Amy Winehouse"),
    ("Love Is a Losing Game", "Amy Winehouse"),
    ("You Know I'm No Good", "Amy Winehouse"),
    ("Tears Dry on Their Own", "Amy Winehouse"),
    ("Creep", "Radiohead"),
    ("High and Dry", "Radiohead"),
    # Indie Folk / Alt Country
    ("The Night We Met", "Lord Huron"),
    ("Ends of the Earth", "Lord Huron"),
    ("Love Like Ghosts", "Lord Huron"),
    ("When the Night Is Over", "Lord Huron"),
    ("Mine Forever", "Lord Huron"),
    ("Mykonos", "Fleet Foxes"),
    ("White Winter Hymnal", "Fleet Foxes"),
    ("Blue Ridge Mountains", "Fleet Foxes"),
    ("Helplessness Blues", "Fleet Foxes"),
    ("Sun It Rises", "Fleet Foxes"),
    ("The Funeral", "Band of Horses"),
    ("No One's Gonna Love You", "Band of Horses"),
    ("Is There a Ghost", "Band of Horses"),
    ("Laundry Room", "Band of Horses"),
    ("Hey", "Pixies"),
    ("Where Is My Mind", "Pixies"),
    ("Here Comes Your Man", "Pixies"),
    ("Debaser", "Pixies"),
    ("Monkey Gone to Heaven", "Pixies"),
    ("I Will Follow You Into the Dark", "Death Cab for Cutie"),
    ("Soul Meets Body", "Death Cab for Cutie"),
    ("Transatlanticism", "Death Cab for Cutie"),
    ("The Sound of Settling", "Death Cab for Cutie"),
    ("Crooked Teeth", "Death Cab for Cutie"),
    ("Such Great Heights", "Postal Service"),
    ("The District Sleeps Alone Tonight", "Postal Service"),
    ("We Will Become Silhouettes", "Postal Service"),
    ("New Slang", "The Shins"),
    ("Caring Is Creepy", "The Shins"),
    ("Phantom Limb", "The Shins"),
    ("Australia", "The Shins"),
    ("Simple Song", "The Shins"),
    ("1901", "Phoenix"),
    ("Lisztomania", "Phoenix"),
    ("If I Ever Feel Better", "Phoenix"),
    ("Runaway", "Kanye West"),
    ("Heartless", "Kanye West"),
    ("Stronger", "Kanye West"),
    ("Gold Digger", "Kanye West"),
    ("All of the Lights", "Kanye West"),
    ("Flashing Lights", "Kanye West"),
    ("Ultralight Beam", "Kanye West"),
    ("Father Stretch My Hands", "Kanye West"),
    ("Bound 2", "Kanye West"),
    ("Roses", "Kanye West"),
    # Film / TV Themes
    ("My Heart Will Go On", "Celine Dion"),
    ("Because You Loved Me", "Celine Dion"),
    ("All by Myself", "Celine Dion"),
    ("The Power of Love", "Celine Dion"),
    ("Eye of the Tiger", "Survivor"),
    ("Danger Zone", "Kenny Loggins"),
    ("Footloose", "Kenny Loggins"),
    ("I'm Alright", "Kenny Loggins"),
    ("St Elmo's Fire", "John Parr"),
    ("Ghostbusters", "Ray Parker Jr"),
    ("Don't You Forget About Me", "Simple Minds"),
    ("Raindrops Keep Fallin on My Head", "B.J. Thomas"),
    ("Mrs Robinson", "Simon and Garfunkel"),
    ("Moon River", "Breakfast at Tiffanys"),
    ("Over the Rainbow", "Judy Garland"),
    ("Singin in the Rain", "Gene Kelly"),
    ("As Time Goes By", "Casablanca"),
    ("The Sound of Music", "Julie Andrews"),
    ("Chim Chim Cher-ee", "Mary Poppins"),
    ("A Spoonful of Sugar", "Mary Poppins"),
    ("Supercalifragilisticexpialidocious", "Mary Poppins"),
    ("Pure Imagination", "Willy Wonka"),
    ("Somewhere Out There", "An American Tail"),
    ("Rainbows", "Kermit the Frog"),
    # More Modern Hits
    ("Heat Waves", "Glass Animals"),
    ("Gooey", "Glass Animals"),
    ("Youth", "Glass Animals"),
    ("Pork Soda", "Glass Animals"),
    ("Space Song", "Beach House"),
    ("Myth", "Beach House"),
    ("Silver Soul", "Beach House"),
    ("Lazarus", "Beach House"),
    ("Dream Pop", "Beach House"),
    ("Black Sheep", "Metric"),
    ("Help I'm Alive", "Metric"),
    ("Gold Guns Girls", "Metric"),
    ("Dead Hearts", "Stars"),
    ("Your Ex-Lover Is Dead", "Stars"),
    ("Oblivion", "Grimes"),
    ("Genesis", "Grimes"),
    ("Close to Me", "The Cure"),
    ("In Between Days", "The Cure"),
    ("Pictures of You", "The Cure"),
    ("A Forest", "The Cure"),
    ("Lullaby", "The Cure"),
    ("Come a Little Closer", "Cage the Elephant"),
    ("Ain't No Rest for the Wicked", "Cage the Elephant"),
    ("Trouble", "Cage the Elephant"),
    ("Cigarette Daydreams", "Cage the Elephant"),
    ("Shake Me Down", "Cage the Elephant"),
    ("Ready to Let Go", "Cage the Elephant"),
    ("Tongue Tied", "Grouplove"),
    ("Float On", "Modest Mouse"),
    ("Dashboard", "Modest Mouse"),
    ("Ocean Breathes Salty", "Modest Mouse"),
    ("The World at Large", "Modest Mouse"),
    ("Dramamine", "Modest Mouse"),
    ("Two Weeks", "Grizzly Bear"),
    ("Ready Able", "Grizzly Bear"),
    ("Feels Like We Only Go Backwards", "Tame Impala"),
    ("Let It Happen", "Tame Impala"),
    ("The Less I Know the Better", "Tame Impala"),
    ("Elephant", "Tame Impala"),
    ("New Person Same Old Mistakes", "Tame Impala"),
    ("Eventually", "Tame Impala"),
    ("Borderline", "Tame Impala"),
    ("Lost in Yesterday", "Tame Impala"),
    ("Is It True", "Tame Impala"),
    ("Breathe Deeper", "Tame Impala"),
    # More classics to round out
    ("Wonderful Life", "Black"),
    ("True", "Spandau Ballet"),
    ("Gold", "Spandau Ballet"),
    ("Relax", "Frankie Goes to Hollywood"),
    ("The Power of Love", "Frankie Goes to Hollywood"),
    ("I Ran So Far Away", "A Flock of Seagulls"),
    ("Don't You Want Me", "Human League"),
    ("West End Girls", "Pet Shop Boys"),
    ("It's a Sin", "Pet Shop Boys"),
    ("Always", "Bon Jovi"),
    ("You Give Love a Bad Name", "Bon Jovi"),
    ("Bed of Roses", "Bon Jovi"),
    ("Runaway", "Bon Jovi"),
    ("Bad Medicine", "Bon Jovi"),
    ("Blaze of Glory", "Bon Jovi"),
    ("I'll Be There for You", "Bon Jovi"),
    ("Pour Some Sugar on Me", "Def Leppard"),
    ("Love Bites", "Def Leppard"),
    ("Photograph", "Def Leppard"),
    ("Animal", "Def Leppard"),
    ("Rock of Ages", "Def Leppard"),
    ("Hysteria", "Def Leppard"),
    ("Nothing Else Matters", "Metallica"),
    ("Enter Sandman", "Metallica"),
    ("One", "Metallica"),
    ("The Unforgiven", "Metallica"),
    ("Fade to Black", "Metallica"),
    ("Master of Puppets", "Metallica"),
    ("Wherever I May Roam", "Metallica"),
    ("Sad but True", "Metallica"),
    ("Sandman", "Metallica"),
    ("Welcome Home Sanitarium", "Metallica"),
    ("Iron Man", "Black Sabbath"),
    ("Paranoid", "Black Sabbath"),
    ("War Pigs", "Black Sabbath"),
    ("N.I.B.", "Black Sabbath"),
    ("Crazy Train", "Ozzy Osbourne"),
    ("Mama I'm Coming Home", "Ozzy Osbourne"),
    ("Mr Crowley", "Ozzy Osbourne"),
    ("Bark at the Moon", "Ozzy Osbourne"),
    ("Ace of Spades", "Motorhead"),
    ("The Trooper", "Iron Maiden"),
    ("Run to the Hills", "Iron Maiden"),
    ("Fear of the Dark", "Iron Maiden"),
    ("Hallowed Be Thy Name", "Iron Maiden"),
    ("Number of the Beast", "Iron Maiden"),
    ("Breaking the Law", "Judas Priest"),
    ("Living After Midnight", "Judas Priest"),
    ("You've Got Another Thing Comin", "Judas Priest"),
    # More modern
    ("Peaches", "Justin Bieber"),
    ("Mood", "24kGoldn"),
    ("Montero", "Lil Nas X"),
    ("Old Town Road", "Lil Nas X"),
    ("Industry Baby", "Lil Nas X"),
    ("Thats What I Want", "Lil Nas X"),
    ("Sunflower", "Post Malone"),
    ("Circles", "Post Malone"),
    ("Better Now", "Post Malone"),
    ("Rockstar", "Post Malone"),
    ("Congratulations", "Post Malone"),
    ("White Iverson", "Post Malone"),
    ("I Fall Apart", "Post Malone"),
    ("Wow", "Post Malone"),
    ("Goodbyes", "Post Malone"),
    ("Psycho", "Post Malone"),
    ("STAY", "Kid Laroi"),
    ("Without You", "Kid Laroi"),
    ("Thousand Miles", "Kid Laroi"),
    ("Middle of the Night", "Elley Duhe"),
    ("abcdefu", "GAYLE"),
    ("Traitor", "Olivia Rodrigo"),
    ("Brutal", "Olivia Rodrigo"),
    ("Favorite Crime", "Olivia Rodrigo"),
    ("Happier", "Olivia Rodrigo"),
    ("Enough for You", "Olivia Rodrigo"),
    ("1 Step Forward 3 Steps Back", "Olivia Rodrigo"),
    ("All I Want", "Olivia Rodrigo"),
    ("Jealousy Jealousy", "Olivia Rodrigo"),
    ("Deja Vu", "Olivia Rodrigo"),
    # Classic Motown / Oldies
    ("Dancing in the Street", "Martha and the Vandellas"),
    ("Heat Wave", "Martha and the Vandellas"),
    ("Nowhere to Run", "Martha and the Vandellas"),
    ("I Can't Help Myself", "Four Tops"),
    ("Reach Out I'll Be There", "Four Tops"),
    ("Baby Love", "The Supremes"),
    ("Stop in the Name of Love", "The Supremes"),
    ("You Can't Hurry Love", "The Supremes"),
    ("Where Did Our Love Go", "The Supremes"),
    ("Be My Baby", "The Ronettes"),
    ("Will You Love Me Tomorrow", "The Shirelles"),
    ("My Boyfriend's Back", "The Angels"),
    ("The Locomotion", "Little Eva"),
    ("Chapel of Love", "Dixie Cups"),
    ("Under the Boardwalk", "The Drifters"),
    ("Save the Last Dance for Me", "The Drifters"),
    ("Up on the Roof", "The Drifters"),
    ("Shout", "Isley Brothers"),
    ("Twist and Shout", "Isley Brothers"),
    ("What a Wonderful World", "Louis Armstrong"),
    ("La Vie en Rose", "Louis Armstrong"),
    ("Mack the Knife", "Louis Armstrong"),
    ("Hello Dolly", "Louis Armstrong"),
    ("Dream a Little Dream", "Ella Fitzgerald"),
    ("Summertime", "Ella Fitzgerald"),
    ("Someone to Watch Over Me", "Ella Fitzgerald"),
    ("Cheek to Cheek", "Ella Fitzgerald"),
    ("God Only Knows", "Beach Boys"),
    ("Good Vibrations", "Beach Boys"),
    ("Wouldn't It Be Nice", "Beach Boys"),
    ("Surfin USA", "Beach Boys"),
    ("Kokomo", "Beach Boys"),
    ("California Girls", "Beach Boys"),
    ("I Get Around", "Beach Boys"),
    ("Fun Fun Fun", "Beach Boys"),
    ("Barbara Ann", "Beach Boys"),
    ("Help Me Rhonda", "Beach Boys"),
    # Miscellaneous popular
    ("Bohemian Rhapsody", "Queen"),
    ("Somebody That I Used to Know", "Gotye"),
    ("Pumped Up Kicks", "Foster the People"),
    ("Use Somebody", "Kings of Leon"),
    ("Sex on Fire", "Kings of Leon"),
    ("Wherever You Will Go", "The Calling"),
    ("How You Remind Me", "Nickelback"),
    ("Photograph", "Nickelback"),
    ("Rockstar", "Nickelback"),
    ("Far Away", "Nickelback"),
    ("Someday", "Nickelback"),
    ("Savin Me", "Nickelback"),
    ("If Everyone Cared", "Nickelback"),
    ("Hero", "Chad Kroeger"),
    ("It's Not Over", "Daughtry"),
    ("Home", "Daughtry"),
    ("Hanging by a Moment", "Lifehouse"),
    ("You and Me", "Lifehouse"),
    ("Everything", "Lifehouse"),
    ("Drops of Jupiter", "Train"),
    ("Hey Soul Sister", "Train"),
    ("Calling All Angels", "Train"),
    ("Drive By", "Train"),
    ("50 Ways to Say Goodbye", "Train"),
    ("When I'm Gone", "3 Doors Down"),
    ("Be Like That", "3 Doors Down"),
    ("Let Me Go", "3 Doors Down"),
    ("Unwell", "Matchbox Twenty"),
    ("3AM", "Matchbox Twenty"),
    ("Push", "Matchbox Twenty"),
    ("If You're Gone", "Matchbox Twenty"),
    ("Bright Lights", "Matchbox Twenty"),
    ("Real World", "Matchbox Twenty"),
    ("Hands", "Jewel"),
    ("Foolish Games", "Jewel"),
    ("You Were Meant for Me", "Jewel"),
    ("Who Will Save Your Soul", "Jewel"),
    ("Torn", "Natalie Imbruglia"),
    ("Luka", "Suzanne Vega"),
    ("Tom's Diner", "Suzanne Vega"),
    ("Fast Car", "Tracy Chapman"),
    ("Give Me One Reason", "Tracy Chapman"),
    ("Talkin Bout a Revolution", "Tracy Chapman"),
    ("Baby Can I Hold You", "Tracy Chapman"),
]

def main():
    # Load existing songs
    data_path = os.path.join(os.path.dirname(__file__), '..', 'data', 'songs.json')
    with open(data_path) as f:
        existing = json.load(f)
    existing_ids = {s['id'] for s in existing}

    import hashlib
    added = 0
    seen_ids = set(existing_ids)

    for i, (title, artist) in enumerate(SONGS):
        sid = make_id(title, artist)
        if sid in seen_ids:
            continue
        seen_ids.add(sid)

        # Deterministic progression selection based on song
        h = int(hashlib.md5(f"{title}{artist}".encode()).hexdigest(), 16)
        prog_idx = h % len(PROGRESSIONS)
        easy_chords, med_chords, adv_chords = PROGRESSIONS[prog_idx]

        es = EASY_STRUMS[h % len(EASY_STRUMS)]
        ms = MED_STRUMS[h % len(MED_STRUMS)]
        ads = ADV_STRUMS[h % len(ADV_STRUMS)]

        entry = {
            'id': sid,
            'title': title,
            'artist': artist,
            'easy': {
                'id': f'{sid}-easy',
                'title': title,
                'artist': artist,
                'level': 'easy',
                'chords': [chord(c) for c in easy_chords],
                'strummingPattern': es[0],
                'strummingDescription': es[1],
                'lyrics': make_lyrics(title, artist, easy_chords),
            },
            'medium': {
                'id': f'{sid}-medium',
                'title': title,
                'artist': artist,
                'level': 'medium',
                'chords': [chord(c) for c in med_chords],
                'strummingPattern': ms[0],
                'strummingDescription': ms[1],
                'lyrics': make_lyrics(title, artist, med_chords),
            },
            'advanced': {
                'id': f'{sid}-advanced',
                'title': title,
                'artist': artist,
                'level': 'advanced',
                'chords': [chord(c) for c in adv_chords],
                'strummingPattern': ads[0],
                'strummingDescription': ads[1],
                'lyrics': make_lyrics(title, artist, adv_chords),
            },
        }
        existing.append(entry)
        added += 1

    with open(data_path, 'w') as f:
        json.dump(existing, f, indent=2)

    print(f"Added {added} new songs ({len(existing)} total)")

if __name__ == '__main__':
    main()
